# Generated by Django 2.1.2 on 2018-12-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_critica_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critica',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
