# Generated by Django 2.1.2 on 2018-12-02 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comentarios', '0003_auto_20181202_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='critica',
            name='like',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
