# Generated by Django 2.1.2 on 2018-12-02 19:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0004_critica_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='critica',
            name='calificacion',
        ),
        migrations.AlterField(
            model_name='critica',
            name='like',
            field=models.ManyToManyField(blank=True, default=1, to=settings.AUTH_USER_MODEL),
        ),
    ]
