# Generated by Django 2.1.2 on 2018-12-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0005_auto_20181202_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='critica',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
