# Generated by Django 2.1.2 on 2018-12-05 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0006_critica_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='critica',
            name='slug',
        ),
    ]
