# Generated by Django 2.1.1 on 2018-10-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='funcion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
