# Generated by Django 2.1.1 on 2018-10-28 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0002_auto_20181028_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='directorio.Departamento'),
        ),
    ]
