# Generated by Django 2.1.2 on 2018-10-10 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clase1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atributo1', models.CharField(max_length=50)),
                ('atributo2', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
